name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: Genez-io/genezio-github-action@v3
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}

      - name: Echo genezio version
        run: genezio --version
      - name: Login
        run: genezio login ${{ secrets.GENEZIO_TOKEN }}
      - name: Deploy
        run: genezio deploy
        env:
          VITE_LEAD_ENDPOINT: ${{ secrets.VITE_LEAD_ENDPOINT }}
          META_CAPI_ACCESS_TOKEN: ${{ secrets.META_CAPI_ACCESS_TOKEN }}

